[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
conditional_escrow_buy = "G6RB5XQwcnXXp34vDot3ERcbGS8RcXUtacMhgXAM8P7n"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[hooks]

[workspace]
members = ["programs/*"]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
