[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
agent_action_guard = "ETLBetVBpHeG3pKKqpCaRQYfQ2opMNEKCsrQUyqgyg6s"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[hooks]
